#ifndef DISTRHO_PLUGIN_INFO_H
#define DISTRHO_PLUGIN_INFO_H

#define DISTRHO_PLUGIN_BRAND        "BGSN"
#define DISTRHO_PLUGIN_NAME         "Arpeggiator"
#define DISTRHO_PLUGIN_URI          "http://moddevices.com/plugins/mod-devel/arpeggiator"
#define DISTRHO_PLUGIN_LV2_CATEGORY "lv2:MIDIPlugin"

#define DISTRHO_PLUGIN_HAS_UI       0
#define DISTRHO_UI_USE_NANOVG       0

#define DISTRHO_PLUGIN_NUM_INPUTS       0
#define DISTRHO_PLUGIN_NUM_OUTPUTS      0
#define DISTRHO_PLUGIN_WANT_MIDI_INPUT  1
#define DISTRHO_PLUGIN_WANT_MIDI_OUTPUT 1

#define DISTRHO_PLUGIN_IS_RT_SAFE       1
#define DISTRHO_PLUGIN_WANT_TIMEPOS     1
#define DISTRHO_PLUGIN_WANT_PROGRAMS    0

#endif // DISTRHO_PLUGIN_INFO_H
